security:
  jwt:
    secret: ${JWT_SECRET:this-is-a-very-long-and-secure-256-bit-jwt-secret-key-that-meets-the-requirements-and-is-more-than-32-bytes-long}
    expiration: 86400000 # 24 hours in milliseconds
    refresh-expiration: 604800000 # 7 days in milliseconds

  rate-limit:
    max-requests: 100
    time-window: 60000 # 1 minute in milliseconds

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type
    allow-credentials: true
    max-age: 3600 